# coding=utf-8
"""
Django settings for ujscert project.

Generated by 'django-admin startproject' using Django 1.9.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#8#h@*a7lj&j9nix2j%@+^n8&dxmsy410z$ehy08idly%m=exb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'docker', 'security.ujs.edu.cn']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ujscert.vul',
    'ujscert.headquarter',

    'captcha',
    'djorm_pgfulltext',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ujscert.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'ujscert.vul.utils.to_review',
            ],
        },
    },
]

WSGI_APPLICATION = 'ujscert.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_ENV_POSTGRES_DB'),
        'USER': os.environ.get('DB_ENV_POSTGRES_USER'),
        'PASSWORD': os.environ.get('DB_ENV_POSTGRES_PASSWORD'),
        'HOST': 'db',
        'PORT': 5432,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-cn'
DATETIME_FORMAT = 'Y-m-d H:i'
DATE_FORMAT = 'Y-m-d'
TIME_ZONE = 'UTC'

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'assets', 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'node_modules'),
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'assets', 'media')

MEDIA_URL = '/media/'

# email

EMAIL_HOST = 'mail.ujs.edu.cn'
EMAIL_HOST_USER = 'user'
EMAIL_SENDER = 'sender'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_PORT = 465

# vul types

VUL_TYPE_CHOICES = (
    ('Web 漏洞', (
        (0, 'SQL 注入'),
        (1, '命令执行'),
        (2, '上传漏洞'),
        (3, '文件包含'),
        (4, '路径穿越'),
        (5, '账户越权'),
        (6, '存储型 XSS'),
        (7, '代码执行'),
    )),
    ('配置不当', (
        (8, '敏感信息泄露'),
        (9, '危险端口开放'),
        (10, '弱口令'),
        (11, '未授权访问'),
    )),
    ('确认的攻击事件', (
        (12, '内容被篡改'),
        (13, 'WebShell 后门'),
        (14, 'Javascript 挂马'),
        (15, 'SEO 黑链')
    )),
    (16, '其他'),
)

CA_CERT = os.path.join(BASE_DIR, 'ca', 'ca.crt')
CA_KEY = os.path.join(BASE_DIR, 'ca', 'ca.key')
CA_KEY_PASSPHRASE = None

SITE_TITLE = '高校信息安全漏洞响应中心'  # 站点名称
SITE_ORG = '江苏大学信息化中心'  # 运营机构
ADMIN_PATH = 'admin'  # 后台路径

# 部署时可使用 deploy_settings 覆盖本文件的配置
try:
    from .deploy_settings import *
except ImportError as e:
    pass
