# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 09:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('x509_cert', models.TextField(blank=True)),
                ('x509_key', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=16)),
                ('url', models.CharField(max_length=1024, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=64), blank=True, default=[], size=None)),
                ('highlighted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=32)),
                ('ver', models.CharField(max_length=64)),
                ('versions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('service', models.CharField(blank=True, max_length=64)),
                ('os', models.CharField(blank=True, max_length=32)),
                ('info', models.CharField(blank=True, max_length=256)),
                ('product', models.CharField(blank=True, max_length=256)),
                ('hostname', models.CharField(blank=True, max_length=128)),
                ('device', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('cpes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=[], size=None)),
                ('certificate', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('banner', models.TextField()),
                ('raw', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=80)),
                ('title', models.TextField(blank=True)),
                ('url', models.CharField(max_length=512)),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('raw_headers', models.TextField(blank=True)),
                ('html', models.TextField()),
                ('app_joint', models.CharField(default='', max_length=256)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField()),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarter.Website'),
        ),
    ]
