# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 09:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ujscert.vul.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=ujscert.vul.models.image_name)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('cost', models.IntegerField()),
                ('reason', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('valid', models.BooleanField(default=True)),
                ('expired', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('purchased', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('event_type', models.IntegerField(choices=[(0, '添加评论'), (1, '更新状态'), (2, '奖励变动')], default=0)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('comment', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('category', models.IntegerField(choices=[('Web 漏洞', ((0, 'SQL 注入'), (1, '命令执行'), (2, '上传漏洞'), (3, '文件包含'), (4, '路径穿越'), (5, '账户越权'), (6, '存储型 XSS'), (7, '代码执行'))), ('配置不当', ((8, '敏感信息泄露'), (9, '危险端口开放'), (10, '弱口令'), (11, '未授权访问'))), ('确认的攻击事件', ((12, '内容被篡改'), (13, 'WebShell 后门'), (14, 'Javascript 挂马'), (15, 'SEO 黑链'))), (16, '其他')])),
                ('anonymous', models.BooleanField(default=False)),
                ('detail', models.TextField(max_length=2048)),
                ('attachment', models.FileField(blank=True, upload_to=ujscert.vul.models.attachment_name)),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已确认'), (2, '已忽略'), (4, '待复核'), (3, '已修复'), (5, '已公开')], default=0)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
                ('fixed', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('response', models.TextField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteHat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('reputation', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('site', models.CharField(blank=True, default='http://', max_length=100, null=True)),
                ('public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousVul',
            fields=[
                ('vul_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vul.Vul')),
                ('ip', models.GenericIPAddressField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            bases=('vul.vul',),
        ),
        migrations.CreateModel(
            name='MemberVul',
            fields=[
                ('vul_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vul.Vul')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vul.WhiteHat')),
            ],
            bases=('vul.vul',),
        ),
        migrations.AddField(
            model_name='timeline',
            name='vul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vul.MemberVul'),
        ),
    ]
