# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import ujscert.vul.models


class Migration(migrations.Migration):

    dependencies = [
        ('vul', '0002_auto_20161005_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='img',
            field=models.ImageField(default='', upload_to=ujscert.vul.models.image_name),
        ),
        migrations.AddField(
            model_name='reward',
            name='intro',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
